project:
  type: website

website:
  title: "know-systemic-racism"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: workplan_summer_2023.ipynb
        text: Workplan

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true

execute:
  debug: true


