# Resources


## Knowledge Graph



## Fatal Encounters with Police



## California Law Enforcement Agencies



## California Law Enforcement Policy Manuals

The information in these manuals specifies policing practices and gives insight into how police are trained to react in the field.

The decision to focus attention on law enforcement policy manuals was influenced by advice to KSR from the former assistant dean of Stanford Law School, the first female African-American judge in Northern California and the first female African-American Superior Court judge in Santa Clara County, California.  
> "Collecting these materials serves an important role in creating an informed populace...When civilians know what is allowed by police policies, they are armed with the knowledge to protect themselves, their loved ones and their community by fighting back against abuse. People must know their rights in order to identify when their rights are being violated." - [Judge LaDoris Hazzard Cordell (Ret.)](https://en.wikipedia.org/wiki/LaDoris_Cordell)

Our partners at the [Electronic Frontier Foundation](https://www.eff.org/), supported the passage of the Senate Bill 978, which required California law enforcement agencies to publish these policies. The bill became fully effective in January 2020 requiring law enforcement agencies to "conspicuously post on their Internet Web sites all current standards, policies, practices, operating procedures, and education and training materials that would otherwise be available to the public if a request was made pursuant to the California Public Records Act.” Not all agencies have complied. We have worked with the EFF to file public records requests for access to the policies. 

KSR also began seeding and collecting webarchive records for policy manuals from California law enforcement agencies in 2020.  

### What is Lexipol?
Once a small company based in Orange County, California, Lexipol has become the leading national law enforcement policymaker. The company created the model policy that is used by 95% of California law enforcement agencies (read more). The influence of Lexipol on law enforcement policy is important to scholars and legal experts because Lexipol promotes its policies as a risk management tool that can reduce legal liability, rather than a tool to improve officer decision-making.  (See Eagly, Ingrid V., and Joanna C. Schwartz. "[Lexipol: The privatization of police policymaking.](https://texaslawreview.org/lexipol/)" TEx. L. REv. 96 (2017): 891.)


## Military Equipment

Gunderson, A., Cohen, E., Schiff, K.J. et al. Counterevidence of crime-reduction effects from federal grants of military equipment to local police. Nat Hum Behav 5, 194–204 (2021). [https://doi-org.stanford.idm.oclc.org/10.1038/s41562-020-00995-5](https://doi-org.stanford.idm.oclc.org/10.1038/s41562-020-00995-5)

